// packages/ui-svelte/src/UlyssesMap.svelte
<script lang="ts">
  import mapboxgl from 'mapbox-gl';
  import maplibregl from 'maplibre-gl';
  import Ulysses from 'ulysses-js';
  import type { MapProps } from '@design/ui-core';
  import { colors } from '@design/ui-core';

  let {
    accessToken,
    steps,
    actions,
    initialStyle,
    initialCenter = [-122.4194, 37.7749] as [number, number],
    initialZoom = 12,
    mapLibrary = 'mapbox',
  }: MapProps = $props();

  // Simple OSM raster style for MapLibre (no API key needed)
  const osmRasterStyle = {
    version: 8,
    sources: {
      'osm-tiles': {
        type: 'raster',
        tiles: ['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],
        tileSize: 256,
        attribution: '© OpenStreetMap contributors',
      },
    },
    layers: [
      {
        id: 'osm-tiles',
        type: 'raster',
        source: 'osm-tiles',
        minzoom: 0,
        maxzoom: 19,
      },
    ],
  };

  // eslint-disable-next-line no-undef
  let mapContainer: HTMLDivElement;
  let map: mapboxgl.Map | maplibregl.Map | null = null;
  let story: Ulysses | null = null;
  let currentStep = $state(0);
  let totalSteps = $state(steps.features.length);

  // Initialize map when container is ready
  $effect(() => {
    if (!mapContainer) return;

    // Clean up existing map
    if (map) {
      map.remove();
      map = null;
      story = null;
    }

    // Initialize the map based on library choice
    if (mapLibrary === 'maplibre') {
      // Use MapLibre GL
      map = new maplibregl.Map({
        container: mapContainer,
        style: initialStyle || osmRasterStyle,
        center: initialCenter,
        zoom: initialZoom,
      });
    } else {
      // Use Mapbox GL (default)
      if (accessToken) {
        mapboxgl.accessToken = accessToken;
      }

      map = new mapboxgl.Map({
        container: mapContainer,
        style: initialStyle || 'mapbox://styles/mapbox/dark-v11',
        center: initialCenter,
        zoom: initialZoom,
      });
    }

    // Initialize Ulysses story when map loads
    map.on('load', () => {
      if (map) {
        story = new Ulysses({
          map: map as any, // Ulysses works with both Mapbox GL and MapLibre GL
          steps,
          actions,
        });

        // Initialize current step from Ulysses
        currentStep = story.current || 0;
      }
    });

    // Cleanup function
    return () => {
      map?.remove();
      map = null;
      story = null;
    };
  });

  // Handlers call Ulysses methods and update state directly
  function handleNext() {
    if (story) {
      story.next();
      currentStep = story.current || 0;
    }
  }

  function handlePrevious() {
    if (story) {
      story.previous();
      currentStep = story.current || 0;
    }
  }

  function handleStep(index: number) {
    if (story) {
      story.step(index);
      currentStep = story.current || 0;
    }
  }

  // Update total steps when steps prop changes
  $effect(() => {
    totalSteps = steps.features.length;
  });

  const currentStepData = $derived(steps.features[currentStep] || steps.features[0]);
</script>

<div
  class="map-container"
  style="--surface-color: {colors.surface}; --text-color: {colors.text}; --primary-color: {colors.primary}"
>
  <div bind:this={mapContainer} class="map"></div>

  <div class="controls">
    <div class="step-info">
      {#if currentStepData?.properties?.title}
        <h3 class="step-title">{currentStepData.properties.title}</h3>
      {/if}
      {#if currentStepData?.properties?.description}
        <p class="step-description">{currentStepData.properties.description}</p>
      {/if}
    </div>

    <div class="navigation">
      <button onclick={handlePrevious} disabled={currentStep === 0} class="nav-button">
        Previous
      </button>

      <div class="step-indicator">
        {#each steps.features as _, index}
          <button
            onclick={() => handleStep(index)}
            class="step-dot"
            class:active={index === currentStep}
            aria-label="Go to step {index + 1}"
          />
        {/each}
      </div>

      <button onclick={handleNext} disabled={currentStep >= totalSteps - 1} class="nav-button">
        Next
      </button>
    </div>
  </div>
</div>

<style>
  .map-container {
    position: relative;
    width: 100%;
    height: 100vh;
    border-radius: 0.5rem;
    overflow: hidden;
  }

  .map {
    width: 100%;
    height: 100%;
  }

  .controls {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 10;
    background: linear-gradient(
      to top,
      var(--surface-color, #020617) 0%,
      var(--surface-color, #020617) 60%,
      transparent 100%
    );
    padding: 2rem 1.5rem 1.5rem;
    color: var(--text-color, #e5e7eb);
  }

  .step-info {
    margin-bottom: 1rem;
    min-height: 4rem;
  }

  .step-title {
    font-size: 1.25rem;
    font-weight: 600;
    margin: 0 0 0.5rem 0;
    color: var(--text-color, #e5e7eb);
  }

  .step-description {
    font-size: 0.875rem;
    color: var(--text-color, #e5e7eb);
    opacity: 0.9;
    margin: 0;
  }

  .navigation {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 1rem;
  }

  .nav-button {
    background-color: var(--primary-color, #0f766e);
    color: white;
    border: none;
    padding: 0.5rem 1rem;
    border-radius: 0.375rem;
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .nav-button:hover:not(:disabled) {
    opacity: 0.9;
    transform: translateY(-1px);
  }

  .nav-button:disabled {
    opacity: 0.4;
    cursor: not-allowed;
  }

  .step-indicator {
    display: flex;
    gap: 0.5rem;
    align-items: center;
  }

  .step-dot {
    width: 0.75rem;
    height: 0.75rem;
    border-radius: 50%;
    border: 2px solid var(--text-color, #e5e7eb);
    background: transparent;
    cursor: pointer;
    transition: all 0.2s ease;
    padding: 0;
  }

  .step-dot:hover {
    transform: scale(1.2);
  }

  .step-dot.active {
    background-color: var(--primary-color, #0f766e);
    border-color: var(--primary-color, #0f766e);
  }
</style>

// packages/ui-react/src/UlyssesMap.tsx
import React, { useEffect, useRef, useState } from 'react';
import mapboxgl from 'mapbox-gl';
import maplibregl from 'maplibre-gl';
import Ulysses from 'ulysses-js';
import type { MapProps } from '@design/ui-core';
import { colors } from '@design/ui-core';
import './UlyssesMap.css';

export interface UlyssesMapProps extends MapProps {
  className?: string;
}

// Simple OSM raster style for MapLibre (no API key needed)
const osmRasterStyle = {
  version: 8,
  sources: {
    'osm-tiles': {
      type: 'raster',
      tiles: ['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],
      tileSize: 256,
      attribution: '© OpenStreetMap contributors',
    },
  },
  layers: [
    {
      id: 'osm-tiles',
      type: 'raster',
      source: 'osm-tiles',
      minzoom: 0,
      maxzoom: 19,
    },
  ],
};

export function UlyssesMap({
  accessToken,
  steps,
  actions,
  initialStyle,
  initialCenter = [-122.4194, 37.7749],
  initialZoom = 12,
  className,
  mapLibrary = 'mapbox',
}: UlyssesMapProps) {
  const mapContainerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<mapboxgl.Map | maplibregl.Map | null>(null);
  const storyRef = useRef<Ulysses | null>(null);
  const [currentStep, setCurrentStep] = useState(0);
  const totalSteps = steps.features.length;

  useEffect(() => {
    if (!mapContainerRef.current) return;

    let map: mapboxgl.Map | maplibregl.Map;

    if (mapLibrary === 'maplibre') {
      // Use MapLibre GL
      map = new maplibregl.Map({
        container: mapContainerRef.current,
        style: initialStyle || osmRasterStyle,
        center: initialCenter as [number, number],
        zoom: initialZoom,
      });
    } else {
      // Use Mapbox GL (default)
      if (accessToken) {
        mapboxgl.accessToken = accessToken;
      }

      map = new mapboxgl.Map({
        container: mapContainerRef.current,
        style: initialStyle || 'mapbox://styles/mapbox/dark-v11',
        center: initialCenter,
        zoom: initialZoom,
      });
    }

    mapRef.current = map;

    // Initialize Ulysses story when map loads
    map.on('load', () => {
      const story = new Ulysses({
        map: map as any, // Ulysses works with both Mapbox GL and MapLibre GL
        steps,
        actions,
      });

      storyRef.current = story;
      setCurrentStep(story.current || 0);
    });

    // Cleanup on unmount
    return () => {
      map.remove();
      mapRef.current = null;
      storyRef.current = null;
    };
  }, [accessToken, steps, actions, initialStyle, initialCenter, initialZoom, mapLibrary]);

  const handleNext = () => {
    if (storyRef.current) {
      storyRef.current.next();
      setCurrentStep(storyRef.current.current || 0);
    }
  };

  const handlePrevious = () => {
    if (storyRef.current) {
      storyRef.current.previous();
      setCurrentStep(storyRef.current.current || 0);
    }
  };

  const handleStep = (index: number) => {
    if (storyRef.current) {
      storyRef.current.step(index);
      setCurrentStep(storyRef.current.current || 0);
    }
  };

  const currentStepData = steps.features[currentStep] || steps.features[0];

  return (
    <div
      className={`map-container ${className || ''}`}
      style={
        {
          '--surface-color': colors.surface,
          '--text-color': colors.text,
          '--primary-color': colors.primary,
        } as React.CSSProperties
      }
    >
      <div ref={mapContainerRef} className="map" />

      <div className="controls">
        <div className="step-info">
          {currentStepData?.properties?.title && (
            <h3 className="step-title">{currentStepData.properties.title}</h3>
          )}
          {currentStepData?.properties?.description && (
            <p className="step-description">{currentStepData.properties.description}</p>
          )}
        </div>

        <div className="navigation">
          <button onClick={handlePrevious} disabled={currentStep === 0} className="nav-button">
            Previous
          </button>

          <div className="step-indicator">
            {steps.features.map((_, index) => (
              <button
                key={index}
                onClick={() => handleStep(index)}
                className={`step-dot ${index === currentStep ? 'active' : ''}`}
                aria-label={`Go to step ${index + 1}`}
              />
            ))}
          </div>

          <button
            onClick={handleNext}
            disabled={currentStep >= totalSteps - 1}
            className="nav-button"
          >
            Next
          </button>
        </div>
      </div>
    </div>
  );
}
